### ISSUE TITLE
Game crash 1.18.1 forge

### ISSUE THREAD

**Issue by SwagRabbit** [HexBugOrion/UnEarthed#79] opened 2022-02-07 11:03 UTC
Game Crashed while exploring/teleporting to origin_Valley from BOP, on a heavely modded minecraft.

Crash report seems to blame unearthed.

https://pastebin.com/9VNvzrNp

Forge 39.0.66

unearthed 2.0.1

**Comment by SwagRabbit** [comment] 2022-02-07 11:23
2nd Crash in the same world at another origin_valley biome, thousands blocks away from the first crash.
(the game doesn't crash while exploring more traditional biomes)

https://pastebin.com/yJV2Aehh

**Comment by lilypuree** [comment] 2022-02-09 05:33
Duplicate of previous issue

**Closed as completed by lilypuree** 2022-02-09 05:33 UTC
