### ISSUE TITLE
I have a Fabric minecraft server and it crashes becuase of Lichen

### ISSUE THREAD

**Issue by NolanJCarr** [HexBugOrion/UnEarthed#44] opened 2021-02-20 23:21 UTC
Whenever someone tries to go and mine, the server crashed, it didn't crash when it first started, but now all of a sudden, it does. I'm on 1.16.5, and I think you should have an option to turn off the lichen or turn it down a little bit, or if you can fix it causing it to crash, I would be fine with that also.

**Comment by lilypuree** [comment] 2021-02-21 00:52
Please provide the full logs...

**Comment by NolanJCarr** [comment] 2021-02-21 02:31
[crash-2021-02-20_19.53.35-server.txt](https://github.com/CorgiTaco/UnEarthed/files/6017097/crash-2021-02-20_19.53.35-server.txt)

**Comment by NolanJCarr** [comment] 2021-02-21 02:31
does that help?

**Comment by lilypuree** [comment] 2021-02-21 03:46
Duplicate of #36

**Closed as completed by lilypuree** 2021-02-21 03:46 UTC
